### ISSUE TITLE
QUESTION: Using Bundler with rbenv-gemset

### ISSUE THREAD

**Issue by ranchodeluxe** [jf/rbenv-gemset#79]
### Goal
Is there someway to tell `bundler` to install all Gemfile gems inside the `.rbenv-gemsets` location? I know that I can use the `bundler --path` option or just hardcode the path into `.bundle/config`. Given these options then `bundler` would create a directory structure inside `~/.rbenv/versions/2.3.1/gemsets/<gemset-name>/gems` directory that includes it's own `bin`, `build_info`, `cache` and `gems` directories. So whatever "metadata" is also included with the gem install seems to be registered with `bundler` but NOT discoverable through `.rbenv-gemsets` path.

### Example Workflow
```bash
$ git clone git://github.com/jf/rbenv-gemset.git $HOME/.rbenv/plugins/rbenv-gemset

$ rbenv gemset init rspecbook

$ cat .rbenv-gemsets
rspecbook

$ $ rbenv gemset active
rspecbook global

$ rbenv gemset list
2.3.1:
  rspecbook
  
$ gem install hello-world
$ ls -lah ~/.rbenv/versions/2.3.1/gemsets/rspecbook/gems/
total 12K
drwxrwxr-x 9 dev dev 4.0K Oct 31 10:09 .
drwxrwxr-x 9 dev dev 4.0K Oct 31 10:09 ..
drwxrwxr-x 5 dev dev 4.0K Oct 31 10:09 hello-world-1.2.0

$ bundle install --path ~/.rbenv/versions/2.3.1/gemsets/rspecbook/gems/
Fetching gem metadata from https://rubygems.org/...
Fetching version metadata from https://rubygems.org/.
Installing execjs 2.7.0
Using bundler 1.13.6
Installing uglifier 3.0.3
Bundle complete! 1 Gemfile dependency, 3 gems now installed.
Bundled gems are installed into /home/dev/.rbenv/versions/2.3.1/gemsets/rspecbook/gems.

$ ls -lah ~/.rbenv/versions/2.3.1/gemsets/rspecbook/gems/
hello-world-1.2.0/ ruby/              

$ ls -lah ~/.rbenv/versions/2.3.1/gemsets/rspecbook/gems/ruby/2.3.0/
build_info/     cache/          doc/            extensions/     gems/           specifications/ 

$ ls -lah ~/.rbenv/versions/2.3.1/gemsets/rspecbook/gems/ruby/2.3.0/gems/
total 16K
drwxrwxr-x 4 dev dev 4.0K Oct 31 10:10 .
drwxrwxr-x 8 dev dev 4.0K Oct 31 10:10 ..
drwxrwxr-x 3 dev dev 4.0K Oct 31 10:10 execjs-2.7.0
drwxrwxr-x 3 dev dev 4.0K Oct 31 10:10 uglifier-3.0.3

$ irb
irb(main):001:0> require 'uglifier';
irb(main):002:0* 
irb(main):002:0> require 'uglifier'
LoadError: cannot load such file -- uglifier
        from /home/dev/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/dev/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from (irb):1
        from /home/dev/.rbenv/versions/2.3.1/bin/irb:11:in `<main>'
irb(main):003:0> 

```

**Comment by jf** [comment]
hi @ranchodeluxe , sorry for the delay. The short answer is yes, by just leting bundler be. Bundler already respects the environment that `rbenv-gemset` respects. Telling bundler to go install that specific directory as a "parent" directory is just wrong. Just use bundler normally, without the `--path`, and you'll see.
