### ISSUE TITLE
`Gem` doesn't see gems set by rbenv-gemset

### ISSUE THREAD

**Issue by AprilArcus** [jf/rbenv-gemset#86]
When I try to execute the `bin/solargraph` installed by RubyGems, I encounter this error:

```
% RBENV_VERSION=2.5.3 RBENV_GEMSETS=solargraph /Users/aprilarcus/.rbenv/versions/2.5.3/gemsets/solargraph/bin/solargraph
Traceback (most recent call last):
	2: from /Users/aprilarcus/.rbenv/versions/2.5.3/gemsets/solargraph/bin/solargraph:23:in `<main>'
	1: from /Users/aprilarcus/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/Users/aprilarcus/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem solargraph (>= 0.a) with executable solargraph (Gem::GemNotFoundException)
```

**Comment by AprilArcus** [comment]
Closing; works properly when invoked as `RBENV_VERSION=2.5.3 RBENV_GEMSETS=solargraph`
